services:


  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=imagedb

    ports:
      - 5000:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 5001:8080

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database